inherit: "config/base.yaml"

dataset:
  image_folder: "/home/grl/datasets/waymo/106762/FRONT/rgb/"
  save_path: "waymo/106762"

tracking:
  # submap_size: 16
  submap_size: 4  # for video
  max_loops: 5

  # min_disparity: 80.0  # fewer kfs
