inherit: "config/base.yaml"

dataset:
  image_folder: "/home/grl/datasets/tum/rgbd_dataset_freiburg1_floor/rgb/"
  save_path: "tum/floor"

tracking:
  submap_size: 8 #4
  max_loops: 1

mapping:
  viewer_mode: "none"
